"""empty message

Revision ID: b4a245fea15f
Revises: 679f234bd5f2
Create Date: 2021-03-10 19:21:23.041884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a245fea15f'
down_revision = '679f234bd5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=True),
    sa.Column('precio', sa.String(length=6), nullable=True),
    sa.Column('peso', sa.String(length=7), nullable=True),
    sa.Column('categoria_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    # ### end Alembic commands ###
